name: C/C++ CI

on:
  push:
    branches: [ "v1.0.0" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: norminette
      run: make norminette
    - name: make
      run: make
    - name: test
      run: make test
      
